import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import PolicyLink from "@/components/PolicyLink";


export const metadata: Metadata = {
  title: "Politica de cookie-uri | Hard Service",
  description: "Politica de cookie-uri a site-ului Hard Service.",
};

export default function PoliticaCookieUri() {
  return (
    <main>
      <SiteHeader />

      <section
        style={{
          maxWidth: "1100px",
          margin: "0 auto",
          padding: "130px 20px 80px",
          minHeight: "80vh",
        }}
      >
        <div
          style={{
            background: "#ffffff",
            color: "#151515",
            borderRadius: "18px",
            padding: "clamp(24px, 5vw, 50px)",
          }}
        >
          <h1
            style={{
              fontSize: "clamp(32px, 5vw, 48px)",
              marginTop: 0,
              marginBottom: "35px",
            }}
          >
            Politica de cookie-uri
          </h1>

       <!-- Start CookieYes cookie policy -->
<style>
  a.cky-banner-element {
    padding: 8px 30px;
    background: #f8f9fa;
    color: #858a8f;
    border: 1px solid #dee2e6;
    box-sizing: border-box;
    border-radius: 2px;
    cursor: pointer
  }
</style>
<h1 class="cookie-policy-h1">Cookie Policy</h1>
<div class="cookie-policy-date-container">
  <p>Effective date: September 10, 2026</p>
  <p>Last updated: September 10, 2026</p>
</div>&nbsp;<h2>Ce sunt cookie-urile?</h2>
<div class="cookie-policy-p">
  <p>Această Politică privind cookie-urile explică ce sunt cookie-urile, cum le folosim, tipurile de cookie-uri pe care le folosim (adică informațiile pe care le colectăm folosind cookie-uri și cum sunt utilizate aceste informații) și cum să gestionați setările cookie-urilor.</p>
  <p>Cookie-urile sunt fișiere text mici utilizate pentru a stoca mici fragmente de informații. Acestea sunt stocate pe dispozitivul dvs. atunci când un site web se încarcă în browser. Aceste cookie-uri ajută la asigurarea funcționării corecte a site-ului web, sporesc securitatea, oferă o experiență mai bună pentru utilizatori și analizează performanța pentru a identifica ce funcționează și unde sunt necesare îmbunătățiri.</p>
</div>&nbsp;<h2>Cum folosim cookie-urile?</h2>
<div class="cookie-policy-p">
  <p>Ca majoritatea serviciilor online, site-ul nostru web utilizează atât cookie-uri proprii, cât și cookie-uri terțe în diverse scopuri. Cookie-urile proprii sunt necesare în primul rând pentru ca site-ul web să funcționeze corect și nu colectează date de identificare personală.</p>
  <p>Cookie-urile terțe utilizate pe site-ul nostru web ne ajută în principal să înțelegem cum funcționează site-ul web, să urmărim cum interacționați cu acesta, să menținem serviciile noastre în siguranță, să livrăm reclame relevante și să îmbunătățim experiența generală a utilizatorului, îmbunătățind în același timp viteza interacțiunilor viitoare cu site-ul nostru web.</p>
</div>&nbsp;<h2>Tipuri de cookie-uri pe care le folosim</h2>
<div class="cky-audit-table-element"></div>&nbsp;<h2 style="margin-bottom: 20px">Gestionați preferințele privind cookie-urile</h2><a class="cky-banner-element">Consent Preferences</a><br />
<div>
  <p>Puteți modifica setările cookie-urilor oricând, făcând clic pe butonul „Preferințe consimțământ” de mai sus. Acest lucru vă va permite să reaccesați bannerul de consimțământ pentru cookie-uri și să vă actualizați preferințele sau să vă retrageți imediat consimțământul.</p>
  <p><br></p>
  <p>În plus, diferite browsere oferă diverse metode de blocare și ștergere a cookie-urilor utilizate de site-uri web. Puteți ajusta setările browserului pentru a bloca sau șterge cookie-urile. Mai jos găsiți linkuri către documente de asistență despre cum să gestionați și să ștergeți cookie-urile în principalele browsere web. Chrome: https://support.google.com/accounts/answer/32050</p>
  <p>Safari: https://support.apple.com/en-in/guide/safari/sfri11471/mac</p>
  <p>Firefox: https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US</p>
  <p>Internet Explorer: https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc</p>
  <p>Dacă utilizați un alt browser web, vă rugăm să consultați documentația oficială de asistență a acestuia.</p>
</div>&nbsp;<p class="cookie-policy-p"> Cookie Policy generated by <a target="_blank" rel="noopener noreferrer" href="https://www.cookiepolicygenerator.ai?utm_source=CPG&utm_medium=footer&utm_campaign=UW">CookieYes - Cookie Policy Generator</a></p>
<!-- End CookieYes cookie policy -->


          
        </div>
      </section>

     <footer>
  <a className="brand brand-v4" href="/#top">
    <b>HARD SERVICE</b>
    <span>MARKETING</span>
  </a>

  <p>Google Ads · Meta Ads · TikTok Ads · Web · Tracking</p>

  <div
    style={{
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "16px",
      flexWrap: "wrap",
      margin: "10px 0 16px",
      fontSize: "12px",
      opacity: 0.7,
    }}
  >
    <PolicyLink href="/politica-confidentialitate">
  Politică de confidențialitate
</PolicyLink>

<span>·</span>

<PolicyLink href="/politica-cookie-uri">
  Politică de cookie-uri
</PolicyLink>
  </div>

  <a href="tel:+40740231358">0740 231 358</a>
</footer>
    </main>
  );
}
